mysql:
  image: mariadb
  ports:
  - 3333:3306 
  environment:
    MYSQL_ROOT_PASSWORD: admin
    container_name: hc_mysql
node:
    build: ./demonode 
    dockerfile: Dockerfile.node
    volumes:
    - ./code:/code
    ports:
    - "8888:8888"
    container_name: hc_node
    command: npm start
php:
    image: php:7-fpm
    volumes:
        - ./code:/code
    links:
        - mysql
    container_name: hc_php
web:
    image: nginx:latest
    ports:
        - "80:80"
        - "443:443"
        - "8080:8080"
    volumes:
        - ./code:/code
        - ./conf/site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
        - node
    container_name: hc_web

