mysql:
    build: ./mariadb
    dockerfile: Dockerfile.node
    ports:
    - 3306:3306
    volumes:
    - ./code/Helpchannel.sql:/docker-entrypoint-initdb.d/Helpchannel.sql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    container_name: hc_mysql
node:
    build: ./demonode 
    dockerfile: Dockerfile.node
    volumes:
    - ./code:/code
    ports:
    - "8888:8888"
    container_name: hc_node
    command: npm start
php:
    build: ./php7-fpm
    dockerfile: Dockerfile.node
    #stdin_open: true
    #tty: false
    #"entrypoint": ["cd /code/Administration"]
    #;composer global require 'fxp/composer-asset-plugin:*';composer update"]
    volumes:
        - ./code:/code
    links:
        - mysql
    container_name: hc_php
web:
    image: nginx:latest
    ports:
        - "80:80"
        - "443:443"
        - "8080:8080"
    volumes:
        - ./code:/code
        - ./conf/site.conf:/etc/nginx/conf.d/site.conf
    links:
        - php
        - node
    container_name: hc_web

