<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '$this->title' => '',
    'Connections History' => 'Historial de Conexiones',
    'Dashboard' => 'Panel de Control',
    'Delete' => 'Borrar',
    'Loading requests for assistance, please wait' => 'Cargando peticiones de asistencia, espere por favor',
    'Login' => 'Iniciar Sesión',
	'RememberMe' => 'Recuerdame',
    'Logout' => 'Salir',
    'My connections history' => 'Mi historial de conexiones',
    'Please fill out the following fields to login' => 'Por favor, rellene los siguientes campos para iniciar sesión',
    'Profiles' => 'Perfiles',
    'Reset Grid' => 'Reiniciar Rejilla',
    'Statuses' => 'Estados',
    'Tracking' => 'Seguimiento',
    'Trackings' => 'Seguimientos',
    'Update Profile: ' => 'Modificar Perfil',
    'profile_id' => 'Perfil',
    'Access Token' => 'Token de acceso',
    'Auth Key' => 'Clave autenticación',
    'Connection' => 'Conexión',
    'Connection Code' => 'Código de Conexión',
    'Connection Trackings' => 'Seguimientos de Conexión',
    'Connections' => 'Conexiones',
    'Connections history' => 'Historial de Conexiones',
    'Create' => 'Crear',
    'Creation Date' => 'Fecha Creación',
    'Creator' => 'Creador',
    'Description' => 'Descripción',
    'End Date' => 'Fecha Fin',
    'Incorrect username or password.' => 'Usuario o contraseña incorrecta',
    'Ldap Username' => 'Usuario Ldap',
    'Machine Name' => 'Nombre de la Máquina',
    'Modification Date' => 'Fecha Modificación',
    'Name' => 'Nombre',
    'Password' => 'Contraseña',
    'Profile' => 'Perfil',
    'Reset' => 'Reiniciar',
    'Search' => 'Buscar',
    'Start Date' => 'Fecha Comienzo',
    'Status' => 'Estado',
    'Technician' => 'Técnico',
    'Update' => 'Modificar ',
    'Update Connection Tracking: ' => 'Modificar Seguimiento Conexión',
    'Update Connection: ' => 'Modificar Conexión: ',
    'Update Status: ' => 'Modificar Estado',
    'Update User: ' => 'Modificar Usuario: ',
    'User' => 'Usuario',
    'Username' => 'Usuario',
    'Users' => 'Usuarios',
];
